/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'content' : string,
  'createdAt' : bigint,
  'authorName' : string,
  'author' : Principal,
  'postId' : bigint,
}
export interface Notification {
  'id' : bigint,
  'notificationType' : NotificationType,
  'createdAt' : bigint,
  'read' : boolean,
  'recipient' : Principal,
  'referenceId' : bigint,
  'message' : string,
}
export type NotificationType = { 'like' : null } |
  { 'comment' : null } |
  { 'follow' : null };
export interface Post {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'published' : boolean,
  'createdAt' : bigint,
  'authorName' : string,
  'author' : Principal,
  'updatedAt' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[string, string, string, boolean], bigint>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAllPublishedPosts' : ActorMethod<[], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPost' : ActorMethod<[bigint], [] | [Post]>,
  'getPostComments' : ActorMethod<[bigint], Array<Comment>>,
  'getPostLikes' : ActorMethod<[bigint], bigint>,
  'getUserFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getUserFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getUserNotifications' : ActorMethod<[], Array<Notification>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasLikedPost' : ActorMethod<[bigint], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'markAllNotificationsAsRead' : ActorMethod<[], undefined>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'updatePost' : ActorMethod<[bigint, string, string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];